### ISSUE TITLE
Failures in siw_proc_mpareq (such as version mis-match) cause segfaults

### ISSUE THREAD

**Issue by gregjoyce** [zrlio/softiwarp#15]
if siw_proc_mpareq() returns a non-zero value, siw_accept_newconn() sets new_cep->listen_cep to NULL. However, a SIW_CM_WORK_MPATIMEOUT work request has already been queued. So when siw_cm_work_handler() runs the state is still in SIW_EPSTATE_AWAIT_MPAREQ and that case does a siw_cep_put on cep->listen_cep which is NULL and causes a segfault.

Also, when siw_accept_newconn() does a goto error it releases the socket but does not set cep->llp.sock to NULL. siw_cm_work_handler() checks for cep->llp.sock != NULL to avoid calling sock_release() but since siw_accept_newconn() did not NULL it, sock_release() is called for the second time on the same socket. This causes a panic.

**Comment by gregjoyce** [comment]
The following changes prevent the crashes but perhaps there are better fixes.

**Comment by gregjoyce** [comment]
$ git diff
diff --git a/kernel/siw_cm.c b/kernel/siw_cm.c
index 8489434..c177e5b 100644
--- a/kernel/siw_cm.c
+++ b/kernel/siw_cm.c
@@ -882,6 +882,7 @@ error:
        if (new_s) {
                siw_socket_disassoc(new_s);
                sock_release(new_s);
+               new_cep->llp.sock = NULL;
        }
        dprint(DBG_CM|DBG_ON, "(cep=0x%p): ERROR: rv=%d\n", cep, rv);
 }
@@ -1065,8 +1066,10 @@ static void siw_cm_work_handler(struct work_struct *w)
                        /*
                         * No MPA request received after peer TCP stream setup.
                         */
-                       siw_cep_put(cep->listen_cep);
-                       cep->listen_cep = NULL;
+                       if (cep->listen_cep != NULL) {
+                               siw_cep_put(cep->listen_cep);
+                               cep->listen_cep = NULL;
+                       }
                        release_cep = 1;
                }
                break;
$

**Comment by gregjoyce** [comment]
[issue15.patch.txt](https://github.com/zrlio/softiwarp/files/1042929/issue15.patch.txt)

**Comment by BernardMetzler** [comment]
Thanks Greg! Applied.... We could also cancel the MPA request timeout, but I prefer your suggestion.

**Comment by BernardMetzler** [comment]
Thanks Greg!
 Applied...
 
 
----- Original message -----From: gregjoyce <notifications@github.com>To: zrlio/softiwarp <softiwarp@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [zrlio/softiwarp] Failures in siw_proc_mpareq (such as version mis-match) cause segfaults (#15)Date: Wed, May 31, 2017 11:00 PM 
if siw_proc_mpareq() returns a non-zero value, siw_accept_newconn() sets new_cep->listen_cep to NULL. However, a SIW_CM_WORK_MPATIMEOUT work request has already been queued. So when siw_cm_work_handler() runs the state is still in SIW_EPSTATE_AWAIT_MPAREQ and that case does a siw_cep_put on cep->listen_cep which is NULL and causes a segfault.
Also, when siw_accept_newconn() does a goto error it releases the socket but does not set cep->llp.sock to NULL. siw_cm_work_handler() checks for cep->llp.sock != NULL to avoid calling sock_release() but since siw_accept_newconn() did not NULL it, sock_release() is called for the second time on the same socket. This causes a panic.
